### ISSUE TITLE
Webpage not refreshing

### ISSUE THREAD

**Issue by geordieeddie** [steve71/RasPiBrew#16]
Hi, I seem to be having an issue with refreshing the webpage, the first time I connect it loads fine, but won't refresh or allow me to reload the page without rebooting the pi, the page begins to load and then just hangs.  New to this and have no idea where to start looking.

Any help would be much appreciated

**Comment by steve71** [comment]
What Web browser are you using?


Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by geordieeddie** [comment]
I've tried it on Firefox, chrome, safari.

**Comment by steve71** [comment]
Did you check your configuration file to see if the settings are correct?  Temperature ID correct?  Have you tried http queries for temperature in the browser (http://your_ip/getstatus/1) ?  Are you using the bootstrap version of the webpage?   


     On Saturday, July 25, 2015 12:55 PM, geordieeddie <notifications@github.com> wrote:
   

 I've tried it on Firefox, chrome, safari.

**Comment by geordieeddie** [comment]
I've tried both the bootstrap and original versions, however I've yet to connect my temp probe as it hasn't arrived yet, would this cause issues with being able to connect to the webpage more than once without having to power cycle the pi?

**Comment by archonic** [comment]
Not having a sensor connected and not referencing the ID of the sensor will cause the page to be unresponsive. The webpage isn't good for anything without any sensors connected and being referenced correctly.

**Comment by geordieeddie** [comment]
Obviously the page serves no purpose without the sensor attached, as it's in the post I decided to set the rest up, and sort port forwarding and a domain so I could control it from work, which is when I came unstuck with the page being unresponsive.  It didn't occur to me that the sensor not being attached would affect the page so much. Thanks for clearing this up for me.
