### ISSUE TITLE
No menu button in android app

### ISSUE THREAD

**Issue by ve3sjk** [steve71/RasPiBrew#27]
I really like your system and would like to port it so that it runs a modified Bradley meat smoker. I currently use Industrial PID for my system. Is there a place for source code for the android application, on my Samsung S5 i don't get a menu button which means i cannot set the IP address to the raspberry PI to establish a connection. I will be implementing RTD temp sensor support for 4 internal meat temp probes + 2 RTD probes for pid controlled heating loops for smoker internal and pellet heater element. Software will control all aspects of a smoking session including feeder motor for the smoke pucks.

**Comment by steve71** [comment]
https://faq.whatsapp.com/en/android/21228643/

For the Samsung S5 you need to long press the app switch button.
